spinframework/spin-docs

- .github/workflows/deploy-preview.yaml
- Adds the deploy preview workflow to get PR previews
- I added SPIN_OCI_ARCHIVE_LAYERS (and comment) because this appeared to be needed when deploying locally; I haven't pinpointed the cause of intermittent unsuccessful deploys without it, but I suspect it's something to do with the massive amount of layers otherwise and perhaps concurrent uploads.
> ci(.github): add deploy preview workflow

- spin.toml
- Removes extraneous redirects in spin.toml
- These were all added over time to the Spin Docs site when part of the [Fermyon Developer site](https://github.com/fermyon/developer).  Those redirects will still exist on the developer site, but will be updated to point to the new/forthcoming Spin Docs home at spinframework.dev.  Therefore, I believe we can remove these.
> ref(spin.toml): update app name, rm redirects

- templates/sidebar.hbs
This attempts to address the issues noted in https://github.com/spinframework/spin-docs/pull/4#issuecomment-2727636664.
* I've reorganised the applications section to writing->structure->building->running (line) testing->observing->troubleshooting (line) config
* I've made triggers their own section, and each trigger is now top-level.  The cron trigger entry is a bit weird @flynnduism, it seems to cite the `/redis-trigger` and `/triggers` page - what was your intent here?
* I've reorganised the API guides section and reverted the name changes (e.g.  I have a _very_ strong preference for "Making HTTP Requests" over "HTTP Interface").
* Moved the reference to a reference section
* Moved a bunch of internals and nerd stuff into a "project" section.  I don't love this name but found things …
> Reorganise table of contents

- content/v2/http-outbound.md
- content/v2/http-trigger.md
- content/v2/javascript-components.md
- content/v2/kv-store-api-guide.md
- content/v2/language-support-overview.md
- content/v2/mqtt-outbound.md
- content/v2/rdbms-storage.md
- content/v2/redis-outbound.md
- content/v2/serverless-ai-api-guide.md
- content/v2/sqlite-api-guide.md
- content/v2/variables.md
- content/v3/http-outbound.md
- content/v3/http-trigger.md
- content/v3/javascript-components.md
- content/v3/kv-store-api-guide.md
- content/v3/language-support-overview.md
- content/v3/mqtt-outbound.md
- content/v3/rdbms-storage.md
- content/v3/redis-outbound.md
- content/v3/serverless-ai-api-guide.md
- content/v3/sqlite-api-guide.md
- content/v3/variables.md
- downloads/install.sh
This ports relevant changes to the Fermyon version of the docs since the site was forked.
The history of the new repo is a bit strange and stuff has been moved without clear traceability so I suspect the merge algorithm has done some guesswork here - I'll look over it when I can see the diff, of course, but please review carefully!
Some changes listed in https://github.com/spinframework/spin-docs/pull/28#issuecomment-2756072851 are omitted as they applied only to stuff in the wasm-languages section which is no longer in the new site.
> Port post-fork changes

- templates/content_navbar.hbs
- Removes the blog and tutorials links from the navbar as they currently lead to 404s
Fixes https://github.com/spinframework/spin-docs/issues/24
> fix(templates): rm missing blog and tutorials links

- .github/workflows/build.yaml
- content/v2/contributing-docs.md
- content/v3/contributing-docs.md
- content/v3/deploying.md
- package.json
- templates/sidebar.hbs
- Add build workflow
- Defer linting for now; ref https://github.com/spinframework/spin-docs/pull/22#pullrequestreview-2718333361
- A few misc. link fixes
> ci(.github): add build.yml; defer linting for now

- .build/check-broken-links.sh
- Re-adds `localhost:16686` to the exemptions, mistakenly removed in https://github.com/spinframework/spin-docs/pull/38
Note: needs https://github.com/spinframework/spin-docs/pull/41 to pass the link checker.
> fix(.build): re-add localhost:16686 to exemptions

- .github/workflows/build.yaml
- .github/workflows/deploy.yaml
- Adds the deploy.yaml to trigger website deploys on merges to main
> ci(.github): add deploy.yaml

- content/v1/install.md
- content/v1/upgrade.md
- content/v2/install.md
- content/v2/upgrade.md
- content/v3/cache.md
- content/v3/install.md
- content/v3/upgrade.md
closes https://github.com/spinframework/spin-docs/issues/26
> Update Homebrew installation to use spinframework tap

- content/v1/ai-sentiment-analysis-api-tutorial.md
- content/v1/key-value-store-tutorial.md
- content/v1/python-components.md
- content/v1/registry-tutorial.md
- content/v1/serverless-ai-hello-world.md
- content/v2/ai-sentiment-analysis-api-tutorial.md
- content/v2/python-components.md
- content/v2/registry-tutorial.md
- content/v2/serverless-ai-hello-world.md
- content/v2/spin-in-pods-legacy.md
- content/v3/ai-sentiment-analysis-api-tutorial.md
- content/v3/migration-v2-v3.md
- content/v3/python-components.md
- content/v3/registry-tutorial.md
- content/v3/serverless-ai-hello-world.md
Closes https://github.com/spinframework/spin-docs/issues/25
> docs(*): Update with Spin/SpinKube Slack channel links

- templates/content_top.hbs
This removes the dependency on `live.js` which only was added on local dev but I am not sure if it added much value. This solves the issue in the case of local dev where we observed that the browser was constantly sending requests for the static assets. 
fixes #50
> remove live.js dependency

- content/index.md
- content/v3/index.md
> Mention Spin is a CNCF project on the landing page

- content/v3/upgrade.md
> Reorganise upgrade documentation

- content/v3/install.md
- content/v3/plugin-authoring.md
- content/v3/quickstart.md
> Switch install and hub links over to new site

- content/v3/deploying.md
> Added new deployment options and CTA for community ones

- .github/workflows/update-cli-reference.yml
I don't believe I can test this outside of main.  Would folks be okay with me merging it as is, and then testing or reverting it?  It should be benign because the action is only manual dispatch, and I believe the only thing it can do is create a PR (which I will review and then close).  Thanks!
> GitHub action to update Spin CLI reference

- static/js/main.js
- templates/content_top.hbs
Adds some basic web analytics to the site, using [plausible](https://plausible.io/spinframework.dev/) and [posthog](https://us.posthog.com/project/143216/) - as there's currently nothing counting visits.
Additionally, I see the existing JS is throwing a variety of console errors, so I removed some scripts that were no longer relevant. The `static/js/main.js` file is pretty sprawling - mostly due to the now defunt search script. There's issue #7 to address that properly, but for now I commented out the portion that initializes it and causes a bunch of errors upon pageload.
> add cookieless analytics to the site

- content/v3/python-components.md
The latest python template uses `componentize-py` 0.16`. This updates the docs to not reference a version to enable templates to update independently of the docs. `requirements.txt` contains the required versions.
> fix: remove outdated componentize-py version

- content/v3/managing-plugins.md
In support of https://github.com/spinframework/spin/issues/2918
> Show how to install plugin from private URL

- content/v3/http-outbound.md
- content/v3/http-trigger.md
- content/v3/kv-store-api-guide.md
- content/v3/language-support-overview.md
- content/v3/python-components.md
- content/v3/rdbms-storage.md
- content/v3/redis-outbound.md
- content/v3/redis-trigger.md
- content/v3/serverless-ai-api-guide.md
- content/v3/sqlite-api-guide.md
- content/v3/variables.md
A user on Discord reported that Python was using v3 of the SDK, but links were going to the v2 docs.  This PR updates links to point to v3.
@dicej I am not sure of the best approach here - if you think it would be better to make the v3 docs the default/root ones on the Python docs site, and change the v2 URLs instead, then let me know and I can do the spin-docs side of it.
> Link Python articles to v3 Python SDK

- package.json
- spin.toml
- static/js/main.js
- static/js/src/modules/search.js
This PR enables using search on the docs.
- It also adds generating the search index for in CI using `spin build`
closes #7
> enable search on docs

- content/index.md
- templates/content_footer.hbs
This is a [sandbox project onboarding](https://github.com/cncf/sandbox/issues/330#issuecomment-2877588374) task.
According to guidelines, we need:
1.  the CNCF trademark in the footer
2. On homepage, the following statement: “We are a Cloud Native Computing Foundation sandbox project."
3. On homepage, the CNCF logo
Guidelines for trademark and CNCF project statement can be found here: https://github.com/cncf/foundation/blob/main/website-guidelines.md
This PR adds 1 and 2. I am not sure how to artfully insert the CNCF logo.
@flynnduism ideally the trademark line would fall under the other footer items; however, i have not been able to finagle the css. Any advise would be appreciated
> Update footer and landing page to meet CNCF website guidelines

- templates/main.hbs
Fixes the spin version selection dropdown. V3 was always the default selected because we were comparing to the wrong url path as the path changed during the migraiton of spin docs.
fixes #104
> fix spin version dropdown behavior

- content/v1/http-trigger.md
- content/v2/http-trigger.md
- content/v3/http-trigger.md
Ref https://github.com/spinframework/spin/issues/3185
> Document spin-client-addr header as optional
